name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Hello Action!
    - name: git status
      run: |
        echo "===========   ENV ============"
        env
        echo "===========   LS ============"
        ls -lth
        echo "$(date): $(whoami)Test" > test.log
        git status
        git config --global user.email "wxdlong@qq.com"
        git config --global user.name "wxdlong"
        git add test.log
        git commit -m "just test"
        git push --set-upstream origin "test"
