on: [push]

jobs:
  hello_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: ./ # Uses an action in the root directory
    - name: Hello action step
      id: hello
      uses: wxdlong/helloAction@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"